### ISSUE TITLE
Support installation on older Python versions

### ISSUE THREAD

**Issue by jaraco** [shopkeep/pytest-black#33]
In pytest-dev/pytest#5272, I encountered an issue with this plugin where it took at least two switches to enable/disable this plugin (one for declaring the plugin, another to enable it by  command line), and getting both of those to work in a cross Python environment was not trivial.

I ended up creating a sister package, [pytest-black-multipy](https://pypi.org/project/pytest-black-multipy), which one can declare as a dependency on Python 2.7+ and pass `--black` to pytest, and the tests will run on all Python versions, invoking `black` on those that support it.

Perhaps this project would consider adopting that functionality natively so that package maintainers could more readily adopt black/pytest-black for projects that still support older Pythons.

**Comment by paddycarey** [comment]
I'm not opposed to this. I think it could be useful until Py2 support finally runs out at the end of this year. If you want to submit a PR i'll review it.
