### ISSUE TITLE
Last commit breaks pytest-black under poetry

### ISSUE THREAD

**Issue by tr11** [shopkeep/pytest-black#45]
The commit https://github.com/shopkeep/pytest-black/commit/584c2d1afde5f3c80027c0c2e093239aaed45c51 for pipenv support breaks existing installs with the poetry package manager.  This is in all similar to the bug described in https://github.com/peterjc/flake8-black/issues/23, which is referenced from the pipenv issue listed on the commit. 

As a workaround, one can do what's mentioned on https://github.com/peterjc/flake8-black/issues/23#issuecomment-635389218, but it would be great if one can just install pytest-black as before the commit above.

**Comment by paddycarey** [comment]
Hi @tr11 thanks for the report.

This is somewhat frustrating, it seems we can support _either_ pipenv or poetry, but not both at the same time until black releases a non-prerelease version. I'm inclined to leave the versioning as-is and add the same workaround note to the README as in the linked flake8-black issue.

I'll try to get to this soon, but happy to accept a PR with the updates too.

**Comment by tr11** [comment]
@paddycarey, I'll submit a PR this weekend to add the info to the readme. Thanks!
