### ISSUE TITLE
pytest-black does not recognize all settings in pyproject.toml

### ISSUE THREAD

**Issue by tobiasraabe** [shopkeep/pytest-black#9]
I have a ``pyproject.toml`` which includes the configuration of ``black``. It seems that changing options like ``skip-string-normalization`` changes the test behaviour of ``pytest-black`` but keywords like ``include`` and ``exclude`` are not recognized. I assume that this behaviour is because ``pytest`` is responsible for file collection. Is it possible to make ``pytest`` aware of this additional configuration or do I have to duplicate the configuration from ``black`` and use the appropriate keywords in the ``pytest`` settings?

**Comment by paddycarey** [comment]
Hey Tobias, thanks for the report. I'm curious how other similar pytest plugins handle this case, let me check out a few and get back to you.

Seems like a reasonable addition, but I'd just like to verify we're doing the same thing as other plugins in this regard.

**Comment by tobiasraabe** [comment]
Hey Patrick,

I know of [``pytest-isort``](https://github.com/moccu/pytest-isort/) which faces the same issue and does not have a workaround either.

**Comment by paddycarey** [comment]
closed by #16
